### ISSUE TITLE
Make it multilingual

### ISSUE THREAD

**Issue by teolemon** [hmontazeri/is-vegan#14]
Make it multilingual

**Comment by veglinus** [comment]
I'd love to help translate this into Swedish to use with my projects, guide me in the right direction :)

**Comment by hmontazerimhp** [comment]
Hi @veglinus,

just make a recommendation. I don't have real direction tbh 😄

**Comment by hmontazeri** [comment]
Hi @veglinus ,

just make a recommendation. I don't have real direction tbh 😄

**Comment by gianantoniopini** [comment]
I'm working on this issue / enhancement in my fork. The first step would be to add support for the ingredients lists in Italian (it) language. Once that is in place it should then be possible to "plug-in" ingredients lists in other languages.

**Comment by hmontazeri** [comment]
@gianantoniopini open to suggestions
