### ISSUE TITLE
Allow users to flag ingredients?

### ISSUE THREAD

**Issue by k4pran** [hmontazeri/is-vegan#20]
Reading the other issues it seems like it will be difficult to avoid false positives and false negatives. It might help to have users of is-vegan to have the option to flag any mistakes to get closer to 100% accuracy?

**Comment by hmontazeri** [comment]
Hi @ryanmccauley211,

That is true! I'm not sure if I understand your point. Anybody can flag ingredients here on github as a PR. 

Could you please give me some detail?

**Comment by k4pran** [comment]
For example if someone decides to use is-vegan as part of a web applet, it would be useful if they could allow their users to flag ingredients if they notice any errors. This means users can report any errors as well as developers.

**Comment by FlorianWendelborn** [comment]
@ryanmccauley211 In this case, I don't think `is-vegan` is the appropriate package to use. As far as I understood, this is just meant to be a quick and dirty checker.

**Comment by hmontazeri** [comment]
@dodekeract agree, for another solution their should a database etc. who knows, maybe I build a solution and feed the data from the database on a regularly back to the npm package...
