### ISSUE TITLE
Feature Request: API

### ISSUE THREAD

**Issue by kjbrum** [hmontazeri/is-vegan#22]
It would be awesome if this list could be made into a public API to be consumed through apps, like my Alfred workflow.

**Comment by Svito-zar** [comment]
I agree. That would be great to have it easily available for everyone

**Comment by hmontazeri** [comment]
API added 

[https://is-vegan.netlify.com/](https://is-vegan.netlify.com/)

**Comment by kjbrum** [comment]
Awesome, thanks @hmontazeri!
