### ISSUE TITLE
Human is a vegan ingredient

### ISSUE THREAD

**Issue by bladespinner** [hmontazeri/is-vegan#3]
![Humans are vegan ingredient](https://i.imgur.com/fXESKPN.png)

Humans seem to be a vegan ingredient

**Comment by hmontazeri** [comment]
But is Human an Ingredient? :)

**Comment by eazel7** [comment]
![how_to_cook_forty_humans](https://user-images.githubusercontent.com/307830/35864458-a7ea7bd6-0b30-11e8-920e-7f80f27a80c4.gif)

**Comment by anulaibar** [comment]
```
throw 'Unknown ingredient'
```

**Comment by hmontazeri** [comment]
Eating human is illegal so I'm going to close this one :)

**Comment by kjbrum** [comment]
Wouldn't it be better to return false if you are checking an "ingredient" that isn't on either of the lists?

**Comment by hmontazeri** [comment]
@kjbrum you can use the ingredientChecker for a more detailed answer... this method just says that it is NOT on the NON-VEGAN list...
